version: '3.1'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dbmigration-test
      POSTGRES_DB: dbmigration-test
      POSTGRES_USER: dbmigration-test
      POSTGRES_HOST_AUTH_METHOD: md5